### ISSUE TITLE
Unable to complete login workflow

### ISSUE THREAD

**Issue by nwhistler** [alfredapp/1password-workflow#1]
### Workflow version

v2022.2

### Alfred version

4.6.5 [1299]

### macOS version

12.3.1

### Debugger output

```alfred_debugger
[ERROR] 2022/04/25 11:50:39 unknown command "account" for "op"
Usage:
  op [command]

Use "op [command] --help" for more information about a command.
./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
Enter the password for REDACTED

Updating items list. It will take a few seconds to complete.
You may close the terminal at any time.
.[ERROR] 2022/04/25 11:50:49 unknown command "account" for "op"
Usage:
  op [command]

Use "op [command] --help" for more information about a command.
./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
```

### More details

I had trouble even getting to the first login. The workflow is not responding to `1p`, but managed to get it to prompt with `:1pextras > manage vaults`

Once I start the process it gives me the errors above.

**Comment by jdevalk** [comment]
Getting the same error:

> Updating items list. It will take a few seconds to complete.
> You may close the terminal at any time.
> ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[ERROR] 2022/04/25 22:12:10 error initializing client: authorization prompt dismissed, please try again
> ./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)

**Comment by vitorgalvao** [comment]
@nwhistler Do you have `/usr/local/bin/op`? Have you ever installed the first version of the 1Password command-line tools? What’s the output of `/usr/local/bin/op --version`?

@jdevalk That error is unrelated.

> error initializing client: authorization prompt dismissed, please try again

What that means is that a prompt was shown and dismissed.

Please open a different issue and be sure to fill the template.

**Comment by nwhistler** [comment]
@vitorgalvao Yes, I did have it installed. `/usr/local/bin/op --version` is showing `1.11.0`

**Comment by vitorgalvao** [comment]
Then you have to install [the newest version](https://1password.com/downloads/command-line/).

I’ll add a check for that in the next release.

**Comment by nwhistler** [comment]
Ah yep, that fixed it. Thank you.

**Comment by TSFoster** [comment]
I had this exact same issue with version `2.0.2` installed. Upgrading to `2.1.0` seems to have fixed it, but I notice that the included binary with this workflow is also `2.0.2`, which seems odd.

It also got me wondering what the upside is to calling the user-installed `op` over your included one?

**Comment by vitorgalvao** [comment]
> I had this exact same issue with version `2.0.2` installed.

Unlikely it was the exact same. It shouldn’t happen with any 2.x version, and @nwhistler even probably installed `2.0.2` yesterday, since `2.1.0` wasn’t out at the time of my reply.

> I notice that the included binary with this workflow is also `2.0.2`, which seems odd.

It’s not odd if you look at the release date. `2.1.0` was released fewer than 24h ago. I am aware of it but didn’t have the chance to update it yet. It isn’t pressing.

> It also got me wondering what the upside is to calling the user-installed `op` over your included one?

I’d rather not have to do it, but at this moment there’s no choice if you want biometric unlock from the CLI. For that to work, the binary *has to* be in `/usr/local/bin/op`.

**Comment by TSFoster** [comment]
Thanks for the explanation about `/usr/local/bin/op`.

I didn't mean 'odd' that you hadn't updated to `2.1.0`, I mean odd that I was having problems with `2.0.2`. By 'exact same' I mean that the error message was exactly the same as @jdevalk. I tried several times and got the exact same error message, found this issue, ran `brew upgrade 1password-cli` to upgrade to `2.1.0`, tried again and it worked first time. I see now that @jdevalk's error was actually different from the original one, although the solution for this also seems to be updating to the latest version of 1password-cli.

**Comment by jdevalk** [comment]
My errors auto resolved 😀 working nicely now!

**Comment by Nickersoft** [comment]
Hey folks, just seeing this issue now after upgrading to Alfred 5 and using the latest version of this workflow (2022.15). Updated to the latest version of `1password-cli` (`op` v2.5.1) and getting:

```
./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700) 
```

after logging in via biometrics, along with:

```
no such file or directory: /Users/tjnickerson/Library/Application Support/Alfred/Workflow Data/com.alfredapp.1password/items.json
```

**Comment by vitorgalvao** [comment]
@Nickersoft Please open a new issue. I’ll need the diagnostics information (run `!1pdiagnostic` in Alfred).
