### ISSUE TITLE
Terminal doesn't open

### ISSUE THREAD

**Issue by SheriffOfNotts** [alfredapp/1password-workflow#10]
### Workflow version

2022.6

### Alfred version

4.6.5 [1299]

### macOS version

Version 12.3.1

### Debugger output

```alfred_debugger
No output - just loging started, then stopped
```

### Terminal output

```terminal_text
Terminal doesn't open
```

### More details

<img width="579" alt="Screenshot 2022-04-29 at 13 30 01" src="https://user-images.githubusercontent.com/16319499/165944558-467e66d6-8b9f-48b1-b144-7fd9a60012e8.png">

No setup option?

**Comment by vitorgalvao** [comment]
Did you change the Workflow’s keyword?

What about `:1pextras`, do you have that?

**Comment by SheriffOfNotts** [comment]
Hi, no I’ve not changed anything. I previously had 1password v7 installed and it did prompt the terminal, but obviously errored. I then realised my mistake, upgraded to v8, removed the workflow, reinstalled it and it’s not prompting for the terminal now.

Can I reset it?

Thanks.

**Comment by vitorgalvao** [comment]
> Can I reset it?

Yes.

**Comment by SheriffOfNotts** [comment]
:1pextras works and if I select Manage Accounts it opens up terminal. Terminal script accepts my credentials, then says "Updating items list. It will take a few seconds to complete." When I type in 1P in Alfred I just get the previous screenshot?

**Comment by vitorgalvao** [comment]
Glad it’s working.
