### ISSUE TITLE
Workflow never updates item list

### ISSUE THREAD

**Issue by princed** [alfredapp/1password-workflow#11]
### Workflow version

2022.7

### Alfred version

4.6.5 [1200]

### macOS version

12.3.1

### Debugger output

```alfred_debugger
[13:01:53.004] Logging Started...
[13:01:58.139] 1Password[Script Filter] Queuing argument '(null)'
[13:01:58.179] 1Password[Script Filter] Script with argv '(null)' finished
[13:01:58.181] 1Password[Script Filter] { "items": [{
  "title": "Sign in and update items",
  "subtitle": "Your terminal will open with instructions",
  "arg": "update_items"
}] }
[13:01:59.442] 1Password[Script Filter] Processing complete
[13:01:59.443] 1Password[Script Filter] Passing output 'update_items' to Conditional
[13:01:59.444] 1Password[Conditional] Processing complete
[13:01:59.444] 1Password[Conditional] Passing output 'update_items' to Run Script
[13:01:59.446] 1Password[Run Script] Processing complete
[13:01:59.446] 1Password[Run Script] Passing output '  export alfred_workflow_data=/Users/<username>/Library/Application\ Support/Alfred/Workflow\ Data/com.alfredapp.1password && export logins_only=0 && /Users/<username>/<settings-sync-folder-path>/Alfred.alfredpreferences/workflows/user.workflow.<workflow-id>/signin.zsh' to Terminal Command
[13:01:59.796] 1Password[Terminal Command] Processing complete
[13:01:59.797] 1Password[Terminal Command] Passing output '  export alfred_workflow_data=/Users/<username>/Library/Application\ Support/Alfred/Workflow\ Data/com.alfredapp.1password && export logins_only=0 && /Users/<username>/<settings-sync-folder-path>/Alfred.alfredpreferences/workflows/user.workflow.<workflow-id>/signin.zsh' to Run Script
```

### Terminal output

```terminal_text
Last login: Mon May  2 12:40:17 on ttys007
  export alfred_workflow_data=/Users/<username>/Library/Application\ Support/Alfred/Workflow\ Data/com.alfredapp.1password && export logins_only=0 && /Users/<username>/<settings-sync-folder-path>/Alfred.alfredpreferences/workflows/user.workflow.<workflow-id>/signin.zsh
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~ sh                                                                                                                                                                                             13:02:02
sh-3.2$ export alfred_workflow_data=/Users/<username>/Library/Application\ Support/Alfred/Workflow\ Data/com.alfredapp.1password && export logins_only=0 && /Users/<username>/<settings-sync-folder-path>/Alfred.alfredpreferences/workflows/user.workflow.<workflow-id>/signin.zsh

---------------------------- INSTRUCTIONS ----------------------------

The official 1Password command-line tool will ask you to sign in.
This is necessary to get the items list for the 1Password Workflow.

For account details, consult your 1Password Emergency Kit:

  https://support.1password.com/emergency-kit/#get-your-emergency-kit

----------------------------------------------------------------------

Updating items list. It will take a few seconds to complete.
You may close the terminal at any time.
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

### More details

I use freshest versions of everything (the workflow, 1password, Alfred, https://github.com/vitorgalvao/custom-alfred-iterm-scripts), but updating items list never finishes. If I run workflow after sign-in attempt it still suggests singing in. 

I also use `fish` and because of that I have to copy&paste sign-in command manually to run it in `sh` (or `zsh`, I tried both) instead, which can be seen in terminal output.

**Comment by vitorgalvao** [comment]
> I use freshest versions of everything (the workflow, 1password, Alfred

When debugging, please always post the exact versions. “Freshest” or “latest” doesn’t provide actionable information and is often wrong.

What’s the exact version of 1Password? Are you using biometric sign in? If so, what’s the result of `/usr/local/bin/op --version`? Also, (roughly) how many 1Password items do you have, across all accounts?

**Comment by vitorgalvao** [comment]
Just released [2022.8](https://github.com/alfredapp/1password-workflow/releases/tag/2022.8). If you install it and run `!1pdiagnostic` then paste the result here, it’ll have the information requested above.

Also, I’ve modified the terminal command so that it invokes Zsh before sending the rest. It should fix your Fish issue.

**Comment by princed** [comment]
> Just released [2022.8](https://github.com/alfredapp/1password-workflow/releases/tag/2022.8).

Thank you Vitor, it actually worked for me this time. I also restarted my machine, and maybe that was the reason.
So probably the issue can be closed now.

> When debugging, please always post the exact versions. “Freshest” or “latest” doesn’t provide actionable information and is often wrong.

Oh sorry, I meant that more like a side-note assuming that all the versions of interest were already mentioned in the issue template.

> Also, I’ve modified the terminal command so that it invokes Zsh before sending the rest. It should fix your Fish issue.

This part didn't work and I had to run `zsh` and copy&paste the command manually:

```
Last login: Thu May  5 11:37:22 on ttys003
  /bin/zsh
  export alfred_workflow_data=/Users/eugenedatsky/Library/Application\ Support/Alfred/Workflow\ Data/com.alfredapp.1password && export logins_only=0 && /Users/eugenedatsky/Library/Group\ Containers/G69SCX94XU.duck/Library/Application\ Support/duck/Volumes/Fastmail/eugene.datsky.me/files/Backup/Alfred.alfredpreferences/workflows/user.workflow.7EAAFC86-1CD3-46AE-9D2B-25BC34C475BB/signin.zsh
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~
```

Maybe it should be something `zsh -c '...'` style?

**Comment by vitorgalvao** [comment]
Glad it’s sorted. As for the Fish case, it was already improved in 2022.9. The current solution should work for you, but please let do me know if it doesn’t.

**Comment by princed** [comment]
Out of curiosity I tried to login with 2022.9, but without any luck, it just doesn't execute until I re-ran it manually:

```
Last login: Thu May  5 12:01:14 on ttys007
  /bin/zsh /var/folders/1h/nmg6dvn92758lw17rldht9140000gn/T/tmp.UyQQL5cD
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~
```

Maybe https://github.com/vitorgalvao/custom-alfred-iterm-scripts is to blame though.

**Comment by vitorgalvao** [comment]
> Maybe https://github.com/vitorgalvao/custom-alfred-iterm-scripts is to blame though.

Seems to be working as expected. It’s either Fish or a setting in your shell/terminal which is preventing it from running the command given before the shell started. Maybe because it starts with spaces? I do that because some people set the shell to not record commands starting with spaces and I don’t want to pollute the history.

**Comment by princed** [comment]
> Maybe because it starts with spaces?

I've just tried removing spaces from terminal command, but it didn't make any difference ¯\\\_(ツ)_/¯
