### ISSUE TITLE
Undefined field in title

### ISSUE THREAD

**Issue by ibigbug** [alfredapp/1password-workflow#13]
### Workflow version

see #12

### Alfred version

see #12

### macOS version

see #12

### Debugger output

```alfred_debugger
{"accountID":"***","vaultID":"***","itemID":"***","url":"https://community.imei.com.au/_ui/system/security/ChangePassword?retURL=%2Fapex%2FCommunitiesLanding&fromFrontdoor=1&setupid=ChangePassword"}},{"uid":"***","title":"wt.social","subtitle":"https://wt.social/register 𐄁 Private 𐄁 undefined","variables":
```

### Terminal output

```terminal_text
NA
```

### More details

<img width="623" alt="image" src="https://user-images.githubusercontent.com/543405/166230194-da89ad12-6d14-4330-88b8-467b2abaf70e.png">

what are the "undefined" fields meant to be?

**Comment by vitorgalvao** [comment]
> what are the "undefined" fields meant to be?

They are the shorthand (a small identifier) for your account.

Which 1Password version are you using? Did you sign in with biometric sign in or password?

**Comment by ibigbug** [comment]
1p version: 

1Password for Mac 8.7.0

80700095, on BETA channel

I enabled biometric sign in but my lid is closed all the time. I got Apple Watch prompt to unlock - sounds like (alt) biometric ?

**Comment by vitorgalvao** [comment]
What’s the output of `/usr/local/bin/op --version`?

**Comment by ibigbug** [comment]
```console
-> % op --version
2.1.0
```

**Comment by vitorgalvao** [comment]
What about `op account list`, what does that show under the shorthand?

**Comment by ibigbug** [comment]
```console
-> % op account list
URL                     EMAIL                    USER ID
***1.1password.com    xx@watfaq.com         ID1
***2.1password.com    xx@gmail.com    ID2
```

**Comment by vitorgalvao** [comment]
No shorthand? Curious. When did you set up those accounts via `op`, was it before you installed 1Password 8?

**Comment by ibigbug** [comment]
no I setup after installing 1Password 8 - however this installation didn't install cmdline, I had to brew cask myself

**Comment by vitorgalvao** [comment]
> however this installation didn't install cmdline

That’s by design. It’s why the Workflow tells you you’re missing the tool. There is one `op` included in the Workflow, but biometric sign in requires (by 1Password) it to be installed in `/usr/local/bin`.

I see the problem. Shorthands aren’t created when using biometric unlock. I’ll do something about that in the next release, which will be out soon.

**Comment by ibigbug** [comment]
I see. good to know. guess that's also why this workflow is like 10mb big

thanks for the great work btw!

**Comment by vitorgalvao** [comment]
> guess that's also why this workflow is like 10mb big

Indeed! The CLI is most of the size.

> thanks for the great work btw!

Thank you for the kind words!

**Comment by vitorgalvao** [comment]
[2022.8 is out](https://github.com/alfredapp/1password-workflow/releases/tag/2022.8), with this fix (now shows the account URL) and the new `!1pdiagnostic` command.
