### ISSUE TITLE
Only able to search 1Password after typing 1p

### ISSUE THREAD

**Issue by pdoak** [alfredapp/1password-workflow#15]
With the old integration ie before 1Password 8, it was possible to bring up 1Password results natively from the search bar without typing 1p beforehand. Is it possible to do this with this new workflow?

**Comment by vitorgalvao** [comment]
See [my reply on the forum](https://www.alfredforum.com/topic/18275-1password-—-search-and-open-1password-items/#comment-94950). It’s not, but the Fallback Search gets you close.

**Comment by pdoak** [comment]
Thank you. That is disappointing. Maybe Alfred will allow such integration in the future.

**Comment by vitorgalvao** [comment]
The next release of the Workflow will also include a Hotkey Trigger.
