### ISSUE TITLE
Workflow does not work when pressing 1p

### ISSUE THREAD

**Issue by ahmeed83** [alfredapp/1password-workflow#17]
### Diagnostic

I have downloaded the workflow and in the first time I saw the command-line asking me to add some info. But by mistake I added wrong sign-in information and the command-line despair. Now I want to do the same thing again but the command line does not show up again when pressing 1p. 

I tried deleting the workflow and downloading it again, disable it and then enable but nothing happend. I even restarted my macbook but no luck. Any idea how to fix it?

### Debugger output

```codeblock
Nothing
```

### Terminal output

```terminal_text
Nothing
```

**Comment by vitorgalvao** [comment]
Run `:1pextras` and choose `Reset accounts`.
