### ISSUE TITLE
"1p" does nothing, produces JSON error in debug log

### ISSUE THREAD

**Issue by JonCrawford** [alfredapp/1password-workflow#27]
### Diagnostic

]697;PreExec### Workflow version
]697;PreExec2022.12
]697;PreExec
]697;PreExec### Alfred version
]697;PreExec4.6.5
]697;PreExec
]697;PreExec### macOS version
]697;PreExec12.4
]697;PreExec
]697;PreExec### Architecture
]697;PreExecarm64]697;PreExec
]697;PreExec
]697;PreExec### Workflow environment variables
]697;PreExecDict {
    auto_refresh = 1
    logins_only = 0
    hostnames_only = 1
}
]697;PreExec
]697;PreExec### 1Password version
]697;PreExec8.7.0
]697;PreExec
]697;PreExec### op version
]697;PreExecIn Workflow: ]697;PreExec2.2.0
]697;PreExecIn /usr/local: ]697;PreExec]697;PreExec
]697;PreExec### Biometric unlock
]697;PreExecNOT enabled
]697;PreExec
]697;PreExec### Custom terminal feature
]697;PreExecEnabled
]697;PreExec
]697;PreExec### Launchd job
]697;PreExecLoaded: -	0	com.alfredapp.1password
]697;PreExecInstalled

### Debugger output

```codeblock
[20:49:02.205] ERROR: 1Password[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:

]697;PreExec]697;PreExec]697;PreExec{"rerun":0.1,"items":[{"uid":"W65YXRTBZ5EABHR5DWY3N7MDU4","title":"✓ xxx@XXXXXXX.com","subtitle":"my.1password.com","arg":"XXXXXXXXXXXXX","variables":{"excluded":false,"userID":"XXXXXXXXX"}},{"uid":"XXXXXXXXXXXXX","title":"✓ xxx@xxxxx.com","subtitle":"Xxx.1password.com","arg":"XXXXXXXXXXXXX","variables":{"excluded":false,"userID":"XXXXXXXXXXXXX"}},{"title":"Update items","subtitle":"Your terminal will open with instructions","arg":"update_items","variables":{"excluded":false,"userID":false}}]}
```

### Terminal output

```terminal_text
¯\_(ツ)_/¯
```

### More details

I've tried removing and reinstalling the latest version a few times. No luck.

**Comment by vitorgalvao** [comment]
Judging the by output of the diagnostic, there is something borked on your side. I don’t know exactly what, but I’d start by investigating [Zsh’s startup files](https://en.wikipedia.org/wiki/Unix_shell#Configuration_files) and look for something regarding the prompt.

Searching for `697;PreExec`, I found [a Reddit thread](https://www.reddit.com/r/emacs/comments/q4yk3n/what_happened_to_my_emacs_prompt/hg25d4u/). It may give you a starting clue.

**Comment by JonCrawford** [comment]
Thanks @vitorgalvao. How does the Alfred<->Shell relationship work? Do I need to restart anything (Alfred, Mac, etc) after I remove the prompt content?

**Comment by vitorgalvao** [comment]
> Do I need to restart anything (Alfred, Mac, etc) after I remove the prompt content?

Probably not, but I’ve never seen your issue before and can’t say for sure.

**Comment by JonCrawford** [comment]
For anyone else viewing this, I believe this issue is caused by [Fig](https://github.com/withfig/fig/). No solution yet.

**Comment by SeparateRecords** [comment]
Hey! I'm on the fig team, this issue is indeed caused by the fig shell integration (we use OSC 697 for metadata, 697 is the alphabet positions of `fig`). I think this might actually a bug with the workflow but not sure, cc @grant0417

How is the workflow executing shell commands? The fig integration shouldn't be active if the shell is launched like `zsh -c 'cmd'`, but will be if it's an interactive session.

The (maybe?) quick solution is to just filter out the escape codes -- the format is
```
OSC 697 ; text BEL
```
... which in JS is `"\x1b]697;SomeTextHere\07"`

**Comment by vitorgalvao** [comment]
> I think this might actually a bug with the workflow but not sure

The Workflow is just sending the commands to the Terminal. However the terminal handles that is up to it, and however the terminal is opened is up to the user.

> The fig integration shouldn't be active if the shell is launched like `zsh -c 'cmd'`, but will be if it's an interactive session.

If an interactive session weren’t needed then neither would a terminal, the Workflow would execute the commands directly.

> The (maybe?) quick solution is to just filter out the escape codes

Fig isn’t popular with users of this Workflow. I don’t want to introduce a workaround for its bug which might affect everyone else by messing with the correct output on 1Password’s tool.

**Comment by JonCrawford** [comment]
@SeparateRecords Wondering if I can put a conditional in my `.zprofile` to not activate Fig when these scripts are run. Any ideas?

**Comment by vitorgalvao** [comment]
@JonCrawford Maybe you can change your [custom terminal integration](https://www.alfredapp.com/help/features/terminal/) script to deactivate Fig. That way it won’t be active when your terminal is invoked from Alfred.

**Comment by SeparateRecords** [comment]
> Maybe you can change your [custom terminal integration](https://www.alfredapp.com/help/features/terminal/) script to deactivate Fig

If you can somehow start it as a non-interactive session then definitely possible!

> Wondering if I can put a conditional in my .zprofile to not activate Fig when these scripts are run. Any ideas?

Yes! For sure. The integration in your .zshrc/.zprofile is just regular shell code, no magic, so you can surround it with a conditional or something like that.

The shell hooks are only added in the "post" line. So you can add a line above it to conditionally execute it, and `fig doctor` shouldn't care about it.
```bash
[[ -z "$is_alfred_workflow" ]] && \     # <-- THIS LINE
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
```
In that example, if `$is_alfred_workflow` is zero characters, the integration is sourced, but if it has _any length at all_ (eg. `is_alfred_workflow=1`) then it's skipped
