### ISSUE TITLE
Can't setup 1Password 8 with Alfred

### ISSUE THREAD

**Issue by DaniStein** [alfredapp/1password-workflow#28]
Sorry, it seems I can't get this to work (again). I am a new user to Alfred and do have 1 Password 8. I downloaded the workflow and did import it. Following the instructions I did type 1p and the terminal window opened. However I typed "no" when asked if I want to add an account manually. Somehow I thought I would be presented with the first option "sign in with biometric unlock".

Now when I try to get back to choose the option to sign in and set up my account it isn't available anymore. I did delete the workflow and imported it back in but same result. I also did try and quit Alfred but also no luck.

**Comment by vitorgalvao** [comment]
> Somehow I thought I would be presented with the first option "sign in with biometric unlock".

That needs to be done in the app.

> Now when I try to get back to choose the option to sign in and set up my account it isn't available anymore.

`:1pextras` → `Reset accounts`.

For future reports, please don’t skip the template. It takes one second to generate and greatly helps me help you. When you skip it, you’re delaying how fast your issue can be looked at and fixed.

**Comment by DaniStein** [comment]
Thank you for the help. Apologies but this is a first time on GitHub for me. What you mean when you say not to skip the template next time. I can't remember having skipped anything. Just came to this page and opened a new issue... Anyway, thanks for the help and it does work now.
