### ISSUE TITLE
Terminal Will not launch to set up items after installing 1password 8 workflow

### ISSUE THREAD

**Issue by Haynesmc** [alfredapp/1password-workflow#30]
I cannot make the new 1Password workflow work. It is downloaded, and I see it in the app under workflows, but when I type option + space bar to pull up Alfred and type in 1p, Alfred simply launches 1Password. Terminal did not open on first run of workflow, so I was unable to set up mine 1password Account.

I ran the diagnostic, and it returned this result:

### Workflow version
2022.12

### Alfred version
4.6.5

### macOS version
12.3.1

### Architecture
i386

### Workflow environment variables
Dict {
    auto_refresh = 1
    logins_only = 0
    hostnames_only = 1
}

### 1Password version
8.7.0

### op version
In Workflow: 2.2.0
In /usr/local: NOT installed

### Biometric unlock
NOT enabled

### Custom terminal feature
NOT enabled

### Launchd job
NOT loaded
NOT installed

I would greatly appreciate any assistance.

**Comment by vitorgalvao** [comment]
> but when I type option + space bar to pull up Alfred and type in 1p, Alfred simply launches 1Password.

That's because you’re picking the app in the results instead of the Workflow. The result you’re looking for will read `Sign in and update items`. If that is not showing up for you, please provide a screenshot and the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) output.

**Comment by Haynesmc** [comment]
Vitor:

Thanks for your reply. I am a total neophyte when it comes to these kinds of operations, so I am going to need my hand held.

What do I need to do to get to the screen that will read "sign in and update items?" In other words, I don't see a way to launch the workflow to get to that point. I understood from the download instructions that window would pop up in terminal after the workflow was installed and I could sign in to my 1Password account and go from there. That did not happen, so how do I get that dialogue up?

And I I have no idea how to run the debugger.

Do you suppose that if I delete the one password workflow and reinstall it I might get the terminal window I need at the conclusion of that process?

Sorry to be so dense dude.

Thanks for your help.

Andy McCue

**Comment by Haynesmc** [comment]
Figured out the solution to this problem. Thanks very much for your help.

Andy McCue
816-809-4529

**Comment by rtvenge** [comment]
For others running into this issue, this comment fixed my problem: https://github.com/alfredapp/1password-workflow/issues/16#issuecomment-1118600915

**Comment by vitorgalvao** [comment]
@rtvenge The issue was different in @Haynesmc’s case, as they did not have custom terminal AppleScript set. The diagnostic checks for that. Another possibility is when Alfred hasn’t been given Automations permission to access the terminal (System Preferences → Security & Privacy → Privacy → Automation), but haven’t found a way (if there even is one) to programatically check for that.
