### ISSUE TITLE
1p fails to load Terminal to sign in and update items

### ISSUE THREAD

**Issue by adamsiem** [alfredapp/1password-workflow#36]
1p fails to load the terminal. (type 1p, select option to 'sign in and update items' and nothing happens. Also fails when starting via :1pextras)

![image](https://user-images.githubusercontent.com/1068543/185458112-60736974-1417-40a8-ae78-588b3c2c34e9.png)

How can I load it manually?
How can I resolve the failure of 1p to activate the terminal?

I have both Terminal and iTerm2 running ZSH default.

Here is my diagnostic:

```
### Workflow version
2022.16

### Alfred version
5.0.1

### macOS version
12.5.1

### Architecture
arm64

### Preferences
Default

### 1Password version
8.8.0

### op version
In Workflow: 2.6.1
In /usr/local: NOT installed

### Biometric unlock
NOT enabled

### Custom terminal feature
Enabled

### Launchd job
Loaded: -	0	com.alfredapp.1password
Installed
```

**Comment by vitorgalvao** [comment]
You have custom code in Alfred Preferences → Features → Terminal. It may be outdated and not working. If you’re using iTerm2, check [Custom Alfred iTerm Scripts](https://github.com/vitorgalvao/custom-alfred-iterm-scripts). If you no longer care for it to be custom, set it to the default `Terminal`.

**Comment by adamsiem** [comment]
That worked!
