### ISSUE TITLE
Trigger without typing 1P

### ISSUE THREAD

**Issue by robgill** [alfredapp/1password-workflow#37]
Is it possible to tweak the workflow so that you don't have to type 1P first? But still see items in alfred?

Also, can you give some more context on why we now need a workflow, but 1Password 7 is still supported as a feature? Assume this is because of changes on 1Password's side forcing the only way to interact is via a workflow?

**Comment by vitorgalvao** [comment]
> Is it possible to tweak the workflow so that you don't have to type 1P first?

It includes a Fallback Search, which you can turn on in Alfred Preferences → Features → Default Results → Setup fallback results.

> Assume this is because of changes on 1Password's side

Correct. 1Password removed the previous third-party integration method and now requires an external command-line. Making the new integration as a Workflow allows us to better support the changes as they happen.

**Comment by kellyarwine** [comment]
I struggled with where to find this so wanted to attach a screenshot of how to do it.

![Image](https://github.com/alfredapp/1password-workflow/assets/2262535/3c874da2-dbe8-42c2-8527-fb2595ad0245)
