### ISSUE TITLE
 Setting up the workflow does not work for me

### ISSUE THREAD

**Issue by daveebbelaar** [alfredapp/1password-workflow#38]
### Diagnostic

Can't run diagnostics

### Debugger output

```codeblock
-
```

### Terminal output

```terminal_text
-
```

### More details

I have 1password 8 and the integration workflow in Alfred 5 installed. However, after selecting "Sign in and update items" the terminal does not open to complete the setup. I am on macOS Monterey 12.4 — MacBook Pro (13-inch, M1, 2020)

Example → https://www.loom.com/share/ef5ed5a3ec0b4b469123241f624608d2

**Comment by vitorgalvao** [comment]
Do you have custom code in Alfred Preferences → Features → Terminal? It may be outdated and not working. If you’re using iTerm2, check [Custom Alfred iTerm Scripts](https://github.com/vitorgalvao/custom-alfred-iterm-scripts). If you no longer care for it to be custom, set it to the default `Terminal`.

**Comment by daveebbelaar** [comment]
Thanks for the prompt response. I don't have any custom code there. Application is set to `Terminal`.

**Comment by vitorgalvao** [comment]
Why can’t you run the diagnostic, and why have you not shared the debugger output? Without those, providing help becomes exponentially harder.

**Comment by vitorgalvao** [comment]
Go into System Preferences → Security & Privacy → Privacy. Scroll down to Automation. Check if Terminal.app is ticked under Alfred.

Why can’t you run the diagnostic, and why have you not shared the debugger output? Without those, providing help becomes significantly harder. Help me help you.

**Comment by daveebbelaar** [comment]
Terminal was not checked there. This solved the problem. Thank you very much!

I think I could not run the diagnostics because 1p was not configured correctly yet. And I was not aware that there is a debugger for Workflows (I am new to this). I understand that it is guesswork then, so I would like to thank you again for your help!
