### ISSUE TITLE
Feature request: shortcut to copy username / password

### ISSUE THREAD

**Issue by mickaelperrin** [alfredapp/1password-workflow#39]
Currently 1password mini app can't provide shortcuts to copy username / password of items without opening the item window.

so, yhis workflow could help a lot.

This is particularly useful for users who are not in a web context and need to quickly access username / password in a terminal context (sudo / ssh without keys...)

Hope this could be implemented easily

**Comment by vitorgalvao** [comment]
See the bottom half of [a previous reply](https://github.com/alfredapp/1password-workflow/issues/9#issuecomment-1144204667).

That said, the [updated version being worked on](https://www.alfredforum.com/topic/18275-1password-—-search-and-open-1password-items/page/6/#comment-98494) should make that possible. It’s on my radar. If you can help test if that version works well for you, I can work on implementing the rest sooner.
