### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by bjorntj** [alfredapp/1password-workflow#40]
Just wondering if I have misunderstood something. I thought that the workflow would update automatically when I update/add things in 1Password but that did not happen. I had to use :1pextras and choose Force Update Items to see the new entries.
Am I missing something or?

**Comment by vitorgalvao** [comment]
> I thought that the workflow would update automatically when I update/add things in 1Password

That is not possible because 1Password doesn’t make that data always available. You have to authenticate to get the data. That’s the major change that makes 1Password 8 require a different approach.

However, the workflows does detect when login data changes (as long as you have the option on in the configuration) and will present you with an `Update Items` at the top of your results, to access that faster.

**Comment by bjorntj** [comment]
ok, but I added a login record but did not see any notification from the workflow, as I remember at least...

**Comment by vitorgalvao** [comment]
It might take a few seconds, or it may be that you’ve missed it, or maybe for some reason it’s further down the list (you can filter for it).

I can’t say more without knowing more about your setup. For example, if you’re not on the latest version of Alfred and the workflow, it may be working differently.

**Comment by bjorntj** [comment]
I have the latest version of both but will double check next time I add a login record and report back if it happens again...
Thx.. :)

**Comment by alexbet** [comment]
`However, the workflows does detect when login data changes (as long as you have the option on in the configuration) and will present you with an Update Items at the top of your results, to access that faster.`

Where do I find this config option to enable it?

**Comment by vitorgalvao** [comment]
> Where do I find this config option to enable it?

It’s on by default. Open the workflow in Alfred Preferences, then click `Configure Workflow` on the top left. It’s the bottom checkbox. When you change the option, you need to Update Items once for it to kick the specified option into gear.
