### ISSUE TITLE
Can't see additional websites for item

### ISSUE THREAD

**Issue by nenych** [alfredapp/1password-workflow#42]
With 1Password7 I had the possibility to open a second or some other website from the 1Password item.
Example:
![CleanShot 2022-11-18 at 18 06 05@2x](https://user-images.githubusercontent.com/10981686/202749322-abbb0747-7ce8-4c8e-9a9e-e054951d957e.png)
But when I search for this item, I can see only the first website:
![CleanShot 2022-11-18 at 18 08 58@2x](https://user-images.githubusercontent.com/10981686/202749736-4fb38d25-94d5-404a-9d47-4299485372c6.png)

**Comment by vitorgalvao** [comment]
Currently unable to test, but could you see if [this version](https://github.com/alfredapp/1password-workflow/files/10045305/1Password.alfredworkflow.zip) works to do what you want? After installing, do `:1pextras` → `Force Update Items` to rebuild the list.

**Comment by nenych** [comment]
It can see all websites, but now I can't open website in my browser, Alfred just opens 1Password app.

**Comment by nenych** [comment]
I do not know how, but I restored released version of app, restarted my laptop and it works.
Thanks a lot.
