### ISSUE TITLE
Is it possibile to avoid to use touch id every time I copy a password?

### ISSUE THREAD

**Issue by leobartowski** [alfredapp/1password-workflow#43]
<img width="489" alt="immagine" src="https://user-images.githubusercontent.com/28431608/205497022-8a7d17b0-a3b8-4133-b7ca-9a2a223b9633.png">
I've this specific settings in the 1Password app.

**Comment by vitorgalvao** [comment]
To do that the workflow would need to save your password, which would then make it accessible from outside 1Password, which would be a potential security risk and negate the point of using 1Password in the first place.

It’s 1Password requiring the authentication, not the workflow, and is working as intended.

**Comment by leobartowski** [comment]
Sorry for the screenshot's language and thank you for the explanation.
Have a great day!

**Comment by vitorgalvao** [comment]
Thank you, you too!
