### ISSUE TITLE
Can't copy or fill OTP when

### ISSUE THREAD

**Issue by rigonatti** [alfredapp/1password-workflow#44]
Would be nice to have copy OTP password since ins a greate feature that 1Password8 can offer.

**Comment by vitorgalvao** [comment]
You can copy the OTP password. By default it’s <kbd>⇧</kbd><kbd>⏎</kbd> but that’s configurable in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).
