### ISSUE TITLE
Search by item fields

### ISSUE THREAD

**Issue by nburyak** [alfredapp/1password-workflow#47]
### Workflow version
2022.21

### Alfred version
5.0.6

### macOS version
13.1

### Architecture
arm64

### Preferences
Dict {
}

### 1Password version
8.9.4

### op version
2.7.1

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

### Debugger output

```codeblock
-
```

### Terminal output

```terminal_text
[11:27:43.240] 1Password[Hotkey] Processing complete
[11:27:43.247] 1Password[Hotkey] Passing output '' to Call External Trigger
[11:27:43.248] 1Password[Script Filter] Running directly with argument ''
[11:27:43.258] 1Password[Script Filter] Queuing argument '(null)'
[11:27:43.353] 1Password[Script Filter] Script with argv '(null)' finished
[11:27:43.359] 1Password[Script Filter] {"items":[{"uid":"ITEM_UID","title":"GitLab CI","subtitle":"node1 𐄁 VaultName 𐄁 my.1password.com","variables":{"accountID":"ACCOUNT_ID","vaultID":"VAULT_ID","itemID":"ITEM_ID","url":"vnc://gitlab:gitlab_ci@node1"}},{"uid":"ITEM_UID","title":"GitLab CI","subtitle":"node2 𐄁 VaultName 𐄁 my.1password.com","variables":{"accountID":"ACCOUNT_ID","vaultID":"VAULT_ID","itemID":"ITEM_ID","url":"vnc://gitlab:gitlab_ci@node2"}},{"uid":"ITEM_UID","title":"GitLab CI","subtitle":"node3 𐄁 VaultName 𐄁 my.1password.com","variables":{"accountID":"ACCOUNT_ID","vaultID":"VAULT_ID","itemID":"ITEM_ID","url":"vnc://gitlab:gitlab_ci@node3"}}]}
```

### More details

It's not possible to search through 1Password item fields (like `subtitle`, `url`, ...), search is performed only through 1Password item's `title`. If I don't include enough info in the `title` while adding it, I won't be able to find the necessary item.

In the former version of 1Password and Alfred workflow it was possible to search by almost any field. I don't always remember the `title` but one of the item's fields matched and I was able to find the necessary item.

**Comment by vitorgalvao** [comment]
> In the former version of 1Password and Alfred workflow it was possible to search by almost any field.

The methodology changed because 1Password itself changed (which is why you now need to install their CLI tool). They no longer provide the data they did and it now needs to be queried and stored. The workflow is not grabbing usernames because those can themselves be sensitive information, plus 1Password saves them in the `additional_information` field which is also used to store the first line of content from secure notes (which are even more sensitive information).

I can expand the filtering to match what you see in the subtitle (all or parts of it) if that helps (let me know), but other than that there’s no other useful non-sensitive information returned by their CLI.

**Comment by nburyak** [comment]
@vitorgalvao thanks for the reply! It would be indeed helpful to expand the filtering to match the subtitle's content.

I think, a lot of people don't remember the titles of the items but they do remember the URL (or domain, which is used to in the subtitle). I think, it will significantly improve the filtering.

Also it will cover the use-case, when the same account is used for several different services. Filtering by URL [subtitle] will give more precise result:
```
        {
            "title": "Apple ID",
            "subtitle": "appstoreconnect.apple.com 𐄁 VaultName 𐄁 my.1password.com",
            "variables": {
                "accountID": "accountID",
                "vaultID": "vaultID",
                "itemID": "itemID",
                "url": "https://appstoreconnect.apple.com"
            }
        },
        {
            "title": "Apple ID",
            "subtitle": "developer.apple.com 𐄁 VaultName 𐄁 my.1password.com",
            "variables": {
                "accountID": "accountID",
                "vaultID": "vaultID",
                "itemID": "itemID",
                "url": "https://developer.apple.com/account"
            }
        }
```

Searching for `apple` is very generic and will give at least 2 results;
Searching for `appstore` will give the exact match for appstoreconnect.apple.com

**Comment by vitorgalvao** [comment]
Good arguments! [This version](https://github.com/alfredapp/1password-workflow/files/10320892/1Password.alfredworkflow.zip) matches URLs too. It will be in the Gallery soon.
