### ISSUE TITLE
Reset Fails ( and subsequent workflows fail unsurprisingly)

### ISSUE THREAD

**Issue by rick-ross-cubic** [alfredapp/1password-workflow#48]
### Workflow version
2023.2

### Alfred version
5.0.6

### macOS version
13.2

### Architecture
i386

### Preferences
Default

### 1Password version
8.9.15

### op version
2.13.1

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

### Debugger output

```codeblock
[10:51:30.557] 1Password[List Filter] Processing complete
[10:51:30.559] 1Password[List Filter] Passing output 'reset_workflow' to Conditional
[10:51:30.560] 1Password[Conditional] Processing complete
[10:51:30.561] 1Password[Conditional] Passing output 'reset_workflow' to JSON Config
[10:51:30.561] 1Password[JSON Config] Processing complete
[10:51:30.562] 1Password[JSON Config] Passing output '(
    "/Users/rick/Library/Application Support/Alfred/Workflow Data/com.alfredapp.vitor.1password",
    "/Users/rick/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.vitor.1password"
)' to Automation Task
[10:51:30.562] ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.trash'
```

### Terminal output

```terminal_text
Don't see how to get this.  Please advise.
```

### More details

I removed my old 1password workflow from alfred.  I reinstalled it right from the gallery.  
Then made this choice:

:1p  >  Reset Workflow 

Nothing complains in alfred but you can see there was a problem.  

Later when I try to "Force update items"  it just goes into an endless loop.

Now I have figured out what happened to some degree.   I had two vaults, one was locked and when the workflow ran it requested access and I granted it.  However the vault was locked and I suspect that is the ultimate issue. 

After unlocking .. everything seems to be fine.

**Comment by vitorgalvao** [comment]
Open the workflow in Alfred Preferences. You’ll see a [red Automation Task](https://www.alfredapp.com/help/workflows/automations/automation-task#colours). Double click it and tell it to update. The reset will work after that.
