### ISSUE TITLE
Search by Category

### ISSUE THREAD

**Issue by wayne-huang-14** [alfredapp/1password-workflow#49]
### Workflow version
2023.2

### Alfred version
5.0.6

### macOS version
12.5.1

### Architecture
i386

### Preferences
Default

### 1Password version
8.9.15

### op version
2.13.1

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

### Debugger output

```codeblock
no failing action
```

### More details

Is there a way to search/filter by category? If there are many items with similar names it would be nice to filter down by category. For example, if I want to search for an Identity but the name is tied to many logins.

**Comment by vitorgalvao** [comment]
Added categories and tags to search in 2022.3.
