### ISSUE TITLE
Search without typing 1p

### ISSUE THREAD

**Issue by ArdjanShero** [alfredapp/1password-workflow#52]
How do i do it so i don't have to type 1p every time i have to search?
Using the old 1Pssword integration there was no need to type  1p and would show the results directly to alfred search

**Comment by vitorgalvao** [comment]
Use the [Fallback Search](https://www.alfredapp.com/help/features/default-results/fallback-searches/).

**Comment by kellyarwine** [comment]
I struggled with where to find this so wanted to attach a screenshot of how to do it.

![Image](https://github.com/alfredapp/1password-workflow/assets/2262535/3c874da2-dbe8-42c2-8527-fb2595ad0245)
