### ISSUE TITLE
Passwort get's no longer copied

### ISSUE THREAD

**Issue by Whitedoteu** [alfredapp/1password-workflow#53]
### Workflow version
2023.5

### Alfred version
5.0.6

### macOS version
13.3.1

### Architecture
arm64

### Preferences
Default

### 1Password version
8.10.4

### op version
2.14.0

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

### Debugger output

```codeblock
[13:55:54.620] 1Password[Script Filter] Processing complete
[13:55:54.647] 1Password[Script Filter] Passing output '' to Arg and Vars
[13:55:54.649] 1Password[Arg and Vars] Processing complete
[13:55:54.650] 1Password[Arg and Vars] Passing output 'Copy Password' to Run Script
[13:55:55.607] ERROR: 1Password[Run Script] [ERROR] 2023/04/24 13:55:55 "qbw7cz35hurhj5zhwzglwd6uku" isn't an item in any vault.
./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
[13:55:55.621] 1Password[Run Script] Processing complete
[13:55:55.623] 1Password[Run Script] Passing output '' to Conditional
```

### More details

Dear 1P Alfred Team, 

I updated today to the newest Version because i wanted to change my Shortcuts.
Now nothing is working.

I tried: 

- Resetting to default
- Removing Workflow completly (Checked that the Folder is gone)
- Added new Login to for testing

I am able to open the 1p Window but not Copy Username or Password to Clipboard

**Comment by vitorgalvao** [comment]
> I updated today to the newest Version

The newest version of what? The workflow or something else?

> [13:55:55.607] ERROR: 1Password[Run Script] [ERROR] 2023/04/24 13:55:55 "qbw7cz35hurhj5zhwzglwd6uku" isn't an item in any vault.

1Password’s CLI tool isn’t finding the item.

In the workflow do `:1pextras` → `Reset Workflow` and try setting it up again.

**Comment by Whitedoteu** [comment]
> > I updated today to the newest Version
> 
> The newest version of what? The workflow or something else?

Sorry I updated the Workflow to the newest Version. I think i was on 2023.3 before. 

> > [13:55:55.607] ERROR: 1Password[Run Script] [ERROR] 2023/04/24 13:55:55 "qbw7cz35hurhj5zhwzglwd6uku" isn't an item in any vault.
> 
> 1Password’s CLI tool isn’t finding the item.
> 
> In the workflow do `:1pextras` → `Reset Workflow` and try setting it up again.

Hi tried that. Still same Error
```
[14:42:28.295] 1Password[Script Filter] Processing complete
[14:42:28.338] 1Password[Script Filter] Passing output '' to Arg and Vars
[14:42:28.338] 1Password[Arg and Vars] Processing complete
[14:42:28.339] 1Password[Arg and Vars] Passing output 'Copy Password' to Run Script
[14:42:34.402] ERROR: 1Password[Run Script] [ERROR] 2023/04/24 14:42:34 "qbw7cz35hurhj5zhwzglwd6uku" isn't an item in any vault.
./1password.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
[14:42:34.407] 1Password[Run Script] Processing complete
[14:42:34.407] 1Password[Run Script] Passing output '' to Conditional
```
1P updated the CLI to show the Vault the PW is read from. 
But it is showing the wrong vault. 
Is the coding maybe missing the vaultid?

**Comment by vitorgalvao** [comment]
> 1P updated the CLI to show the Vault the PW is read from.
> But it is showing the wrong vault.

Can you be more specific about what you’re seeing? How have you determined it’s showing the wrong vault? And *what* is showing the wrong vault? The workflow or the CLI? In which context?

> Is the coding maybe missing the vaultid?

No, all vaults are considered. Go into `:1pextras` again. You can manage vaults and accounts in there.

Are you able to use `op` from the command-line?

**Comment by Whitedoteu** [comment]
What i did was:
I looked into the Coding from you and found how to test it without going through the workflow. 
I opend a Terminal and wrote this:
`op item get --field label=${password} qbw7cz35hurhj5zhwzglwd6uku`
When executing i get this Window:
![CleanShot 2023-04-24 at 14 54 43](https://user-images.githubusercontent.com/16068109/234002278-0d40f021-d542-4e5d-ba9f-37625d288360.png)
Sorry can not change the Language:
But in short it asks for Permission for the wrong Account. 

After granting Permission via TouchID i get the same Error in the Terminal:
`[ERROR] 2023/04/24 14:55:51 "qbw7cz35hurhj5zhwzglwd6uku" isn't an item in any vault.`

**Comment by vitorgalvao** [comment]
Thank you, that helps and was quite clear. Does [this version](https://github.com/alfredapp/1password-workflow/files/11310910/1Password.alfredworkflow.zip) work for you? If it doesn’t on the first try, try after another `Reset Workflow`.

**Comment by vitorgalvao** [comment]
Thank you, that helps and was quite clear. If you downloaded the earlier version, ignore it as it was missing a piece.

Does [this one](https://github.com/alfredapp/1password-workflow/files/11310990/1Password.alfredworkflow.zip) work correctly for you? If it doesn’t on the first try, try after another `Reset Workflow`.

**Comment by vitorgalvao** [comment]
> ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.trash'

You need to install the [Automation Tasks](https://www.alfredapp.com/help/workflows/automations/automation-task/) for that. The page teaches you how. In Alfred 5.1 (currently in pre-release) this will be simpler and can be set to automatically  update.

Is `Heer Family` a vault or an account? Because those are different things.

Try [this one](https://github.com/alfredapp/1password-workflow/files/11311363/1Password.alfredworkflow.zip).

**Comment by Whitedoteu** [comment]
I got 2 Accounts with 2-3 Vaults each. 

Your new Version is working. :)
I now get Username and PW.

I still get a strange Log when using the Reset after installing the Autmated Tasks:
```
[16:35:09.725] 1Password[List Filter] Processing complete
[16:35:09.730] 1Password[List Filter] Passing output 'reset_workflow' to Conditional
[16:35:09.731] 1Password[Conditional] Processing complete
[16:35:09.731] 1Password[Conditional] Passing output 'reset_workflow' to JSON Config
[16:35:09.732] 1Password[JSON Config] Processing complete
[16:35:09.733] 1Password[JSON Config] Passing output '(
    "/Users/tobiasheer/Library/Application Support/Alfred/Workflow Data/com.alfredapp.vitor.1password",
    "/Users/tobiasheer/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.vitor.1password"
)' to Automation Task
[16:35:09.733] 1Password[Automation Task] Running task 'Send to Trash' with arguments (
    "/Users/tobiasheer/Library/Application Support/Alfred/Workflow Data/com.alfredapp.vitor.1password"
). Argument warnings: (
    "Passed in file '/Users/tobiasheer/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.vitor.1password' does not exist, discarding"
)
[16:35:10.071] 1Password[Automation Task] Processing complete
[16:35:10.079] 1Password[Automation Task] Passing output '' to Arg and Vars
[16:35:10.081] 1Password[Arg and Vars] Processing complete
[16:35:10.082] 1Password[Arg and Vars] Passing output '' to Run Script
```
File does not exist Error.

But the main Issue is no solved. If you need me to test more I'm happy to help.

**Comment by vitorgalvao** [comment]
Great! The new version is now out.

Thank you for the fast replies and for looking into the internals to run the commands manually, which sped up the whole process.

Don’t worry about the warning, it’s expected when doing a reset but there’s no cache.
