### ISSUE TITLE
Sorting 1P items

### ISSUE THREAD

**Issue by doitlikejustin** [alfredapp/1password-workflow#58]
Is it possible to sort items when running `1p`? It seems like the items now are shown randomly.

Thanks

**Comment by vitorgalvao** [comment]
The order of items is learned by Alfred based on what you type and select. That only changes when an update is detected (if that option is selected) to show the update item at the top. You’re meant to navigate the items by filtering, not scrolling.

**Comment by doitlikejustin** [comment]
I have many accounts with lots of duplicates. For example, I have over a dozen Google accounts and when I search for `1p google` it would be nice if the filtered order was sorted so I could easily find the one I need in the list.

The 2nd issue that makes this more confusing to filter (especially with lots of password) is that if an item has multiple URLs (see below screenshot)
<img width="457" alt="Markup 2023-05-31 at 06 02 19" src="https://github.com/alfredapp/1password-workflow/assets/637056/e5f35baa-674f-4c63-819f-5acb31a47514">

...then it will list the item that many times when searching (see below screenshot).
<img width="764" alt="Markup 2023-05-31 at 06 08 10" src="https://github.com/alfredapp/1password-workflow/assets/637056/bc6605af-f32d-42ac-b775-3d54c464c10b">

I think have the option to only show just the 1st password would be ideal (or at least having the option to do so)

**Comment by vitorgalvao** [comment]
> when I search for 1p google it would be nice if the filtered order was sorted so I could easily find the one I need in the list.

As per above, Alfred [will learn what you pick](https://www.alfredapp.com/help/kb/understanding-result-ordering/). See point 2 in particular, you can type your search query in a way that certain combinations will bring certain accounts to the top.

> if an item has multiple URLs (see below screenshot)

That’s by design and was specifically requested as a feature. It works that way because each URL completes on a different website. I’ll give it some thought regarding making it an option, but the way it works now is more versatile and preferable for most people.

**Comment by doitlikejustin** [comment]
> That’s by design and was specifically requested as a feature. It works that way because each URL completes on a different website. I’ll give it some thought regarding making it an option, but the way it works now is more versatile and preferable for most people.

Since the URLs are shortened, it's very hard to tell what URL goes where. For example, in my example above it just says "accounts.google.com" 4 times. And these 4 URLs were generated by 1Password automatically when creating the Google account. I'm sure for most it fine if there are only a few dozen passwords, but for people with thousands of passwords and some with many URLs in each it can get overwhelming when searching. Thanks for considering, though. I can work on a PR if you are interested.

**Comment by vitorgalvao** [comment]
> Since the URLs are shortened

By default. You can disable that in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) (second from the bottom).

**Comment by doitlikejustin** [comment]
Ok. I would still like to request the feature of only showing 1 URL per password item. 

My use case is searching `1p` and copying the password or copying the OTP. I never "open" a password via the Alfred box. And I feel like many people will have a similar use case.

**Comment by vitorgalvao** [comment]
> I would still like to request the feature of only showing 1 URL per password item.

Please test [this version](https://github.com/alfredapp/1password-workflow/files/11629787/1Password.alfredworkflow.zip) and report back. Untick the `Repeat entries with multiple websites` checkbox in the configuration and run `:1pextras` →  `Fore Update Items` to rebuild the cache.

**Comment by doitlikejustin** [comment]
@vitorgalvao I've tried this version out and it works excellent! Did not see any issues with it. 

Thank you!

**Comment by vitorgalvao** [comment]
Thank you for the test. The new version will be out in the Gallery today.
