### ISSUE TITLE
feature request: include usernames in items

### ISSUE THREAD

**Issue by jason-green-io** [alfredapp/1password-workflow#59]
will allow to search for and identify specific usernames in vaults/accounts

**Comment by vitorgalvao** [comment]
Usernames are [deliberately not saved](https://github.com/alfredapp/1password-workflow/issues/47#issuecomment-1367360760) out of caution:

> The workflow is not grabbing usernames because those can themselves be sensitive information, plus 1Password saves them in the `additional_information` field which is also used to store the first line of content from secure notes (which are even more sensitive information).

They weren’t available in the previous integration either because 1Password didn’t make them available. It was discussed adding that as an option but it was [ultimately decided against](https://github.com/alfredapp/1password-workflow/pull/19#issuecomment-1119611223):

> The field wasn’t available in the previous third-party integration, and for good reason: usernames can themselves be sensitive information and in the case of Secure Notes, that field shows the first line. We can make the argument that because it’s an option, the Workflow can give the user the flexibility of which data to keep, but saving sensitive data should not be turned on by default. Given the broad range of users (many of which not computer experts) this Workflow is geared for and the potential sensitivity of the data, I’m reticent to even provide the option.

**Comment by philocalyst** [comment]
Okay, reading through the other issues now, I see your points. My personal view is that the workflow should fall back to how 1Password the app handles these gray areas. This idea of debugging and accidentally sharing critical information is of course an actual reality, and usernames are indeed some level of extra security, but by taking this stance, the workflow inadvertently becomes more secure than the actual app it interfaces with; **as in 1Password usernames are un-obfuscated.** I don't believe the threat of this case of leaked usernames is any more relevant to 1Password than to this workflow, but this doesn't provide even an option for what is the default of the thing it is emulating.

Granted, 1Password does also have the option to have passwords displayed in this same manner, but I would view those as "strictly critical" and not worth exposing to Alfred through a simple toggle. Same as the current situation with the clipboard. This is just my personal ethos, I respect you as the workflow owner @vitorgalvao. Hope you can sympathize!

**Comment by vitorgalvao** [comment]
> My personal view is that the workflow should fall back to how 1Password the app handles these gray areas.

And this is exactly what 1Password did when they supported third-party integrations from the app, they *didn’t* provide usernames. Because 1Password did that is precisely what got me first thinking about not saving usernames.

Now that everyone needs to handle the integrations themselves, the CLI provides access to any information one wants so we need to be extra careful about what is collected. You can’t compare what the app does when unlocked to an outside cache. The workflow follows the previous 1Password behaviour when in doubt.

**Comment by philocalyst** [comment]
I'm confused -- the 1Password integration provides usernames as much as it provides passwords. Your workflow is as "unlocked" as it is when it accesses a password as it is when it accesses a username. This isn't an outside cache, it's an application integrated with the 1Password command line interface. As an example, an official 1Password integration is with the universal clipboard (What I would say is much more alike to an outside cache). An option that was live even during the days of ios applications reading from the clipboard without permissions. 

The clipboard is an interface that is much easier for an average user to "shoot themselves in the foot with" in my opinion. That sketchy data reading from the past is just the best example of it. Here in the github issues, you have provided instructions on how to remove some of the securities you have in place to enable that. 

This is what I mean by following the example of 1Password -- treating yourself like a real app. After all, 1Password itself is just a front-end to an underlying database. All this option is asking for is a way to access a low-risk, default, UI pattern. I could even help you design a very threatening pop-up, and I understand why this shouldn't be a default, but a solution should exist.

▰▰▰▰▰
Miles Wirht 🙃

**Comment by vitorgalvao** [comment]
You are misunderstanding and conflating a number of things. Forgive me, but correcting everything would require going too far back and take too long. You are contradicting my explanation on things I programmed myself, but I know how the code I wrote works and why it was built that way.

The debate on including usernames has been had and settled. The decision wasn’t made lightly, it came after long consideration. The workflow has thousands and thousands and thousands of users and less than a handful has asked for usernames in subtitles. Those who did so far understood and accepted why they are not included. 1Password themselves didn’t provide usernames when they managed third-party integrations up to v7 (they no longer do, the CLI is an entirely different beast), they clearly understood the possible sensitivity of the data. With something of this nature, erring on the side of caution is the best choice. I’m sure *you* are equipped to understand the risks, but many many many people are not, and this workflow aims to serve them all equally securely. I take privacy and security very seriously.

The workflow is open-source so you are welcome to change it however you see fit on your local set up (though naturally I can only offer support for pristine unmodified versions). But officially I have no current plans to add that foot gun, even as an option.

I hope that makes the position clear. Again, apologies for not going through the rabbit hole of clarifying every misconception, but it would genuinely take an unreasonable amount of time to convey in text (I know how thorough I get; look how long this post already is) and I do have other people to support and things to finish today. If we ever meet in person, please do ask and I’ll be more than happy to explain everything in detail, step by step, until we’re both satisfied with having the same context.

Have a great week!
