### ISSUE TITLE
Old version of password is being copied, not current one.

### ISSUE THREAD

**Issue by mjazwiecki** [alfredapp/1password-workflow#60]
### Workflow version
2023.7

### Alfred version
5.1.1

### macOS version
13.4

### Architecture
arm64

### Preferences
Dict {
    modifier_none = Copy Password
}

### 1Password version
8.10.7

### op version
2.17.0

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

### Debugger output

```codeblock
[08:40:33.265] 1Password[Script Filter] Processing complete
[08:40:33.314] 1Password[Script Filter] Passing output '' to Conditional
[08:40:33.314] 1Password[Conditional] Processing complete
[08:40:33.315] 1Password[Conditional] Passing output '' to Arg and Vars
[08:40:33.315] 1Password[Arg and Vars] Processing complete
[08:40:33.316] 1Password[Arg and Vars] Passing output 'Copy Password' to Run Script
[08:40:46.235] 1Password[External] Processing complete
[08:40:46.242] 1Password[External] Passing output '' to Run Script
[08:40:46.377] 1Password[Run Script] Processing complete
[08:40:46.386] 1Password[Run Script] Passing output '' to Run Script
[08:40:46.865] 1Password[Run Script] Processing complete
[08:40:46.870] 1Password[Run Script] Passing output '' to Conditional
```

### More details

when 1password contains login with password history, the workflow fetches the old version of the password instead of a new one.

**Comment by vitorgalvao** [comment]
I can’t reproduce. The workflow uses the official 1Password command-line tool, and as far as I can tell there isn’t even a way to ask for historic password data. A possible explanation would be that something went wonky on 1Password’s side and they’re returning the old password for some reason.

Here’s how you can check: Open [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) and list your items. You’ll see a long JSON with the information. Look for the item in question[^1] and copy the `uid` value, it will be something like `834b34dcda397430e76a9ba053`.

Now [open a terminal](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac) and run `op item get THE_UID_HERE` (example: `op item get 834b34dcda397430e76a9ba053`) and look at what the password says. That’s what the workflow is asking for and it’s provided by the 1Password command-line tool. If it’s returning old information, it needs to be fixed on their side.

[^1]: It helps if you action it a couple of times to bring it to the top, as it’ll be easier to find.

**Comment by mjazwiecki** [comment]
ok, so I dived into what is happening, and you are right, there were some oddities on 1p side:

there are three fields when you do `op item get [uid]`
```
Fields:
  password:           [redacted]
  newPassword:        [redacted]
  confirmPassword:    [redacted]
```
each of them, for some mysterious reason, were pointing to one my previous passwords. to fix it I run:
```
op item edit [uid] password=[redacted]  
op item edit [uid] newPassword=[redacted]
op item edit [uid] confirmPassword=[redacted]
```
voila!
