### ISSUE TITLE
Update dialog to indicate 1password-cli from `brew install` doesn't work

### ISSUE THREAD

**Issue by bdruth** [alfredapp/1password-workflow#65]
### Feature details

Spun my wheels a bit on the "you need to install the 1password cli" dialog, since I already have and use elsewhere the 1password-cli - but it's installed via `brew` ... and this doesn't work (maybe you know why?) - the `brew` method is also the default recommended on the page that the dialog links to from agilebits/1password - so it's doubly confusing. Maybe just a note in the dialog that you need the manually installed version? After I installed that, everything was cool.

**Comment by vitorgalvao** [comment]
Which command did you use to install with Homebrew? Where was the CLI after that?

**Comment by vitorgalvao** [comment]
Let’s continue at the other issue. Could you please confirm if [biometric unlock still works for you](https://github.com/alfredapp/1password-workflow/issues/64#issuecomment-1712453349)?

**Comment by vitorgalvao** [comment]
[The other issue](https://github.com/alfredapp/1password-workflow/issues/64) is covering the situation. Please refer to that.
