### ISSUE TITLE
Unable to view or sync items

### ISSUE THREAD

**Issue by JohnMaguire** [alfredapp/1password-workflow#67]
### Workflow version
2023.11

### Alfred version
5.1.2

### macOS version
13.5.2

### Architecture
arm64

### Preferences
Dict {
}

### 1Password version
8.10.13

### op version
2.21.0

### Launchd job
NOT loaded
NOT installed

### Debugger output

```codeblock
[11:35:32.502] 1Password[Junction] Processing complete
[11:35:32.504] 1Password[Junction] Passing output 'update_items' to Automation Task
[11:35:32.506] ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/macOS/app.running'
```

### More details

I was previously using the 1Password workflow just fine. I saw there was an update for users of 1Password 8, so I decided to bite the bullet. Unfortunately, now all I get is "Sign in and update items." When I hit Enter on that result, nothing happens.

![Menu Items](https://i.imgur.com/EGcSdXY.png)

I tried the debug options in `:1pextras` (Reset Workflow, Force Update Items), but they don't seem to have any effect. Manage Accounts and Manage Vaults show my personal and work account, both selected.

Any help would be greatly appreciated!

```
macOS 13.5.2
1Password for Mac 8.10.13
1Password by Vitor Galvão v2023.11
Alfred 5.1.2 [2145]

❯ op --version
2.21.0
```

**Comment by vitorgalvao** [comment]
> [11:35:32.506] ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/macOS/app.running'

You need to [install the Automation Tasks](https://www.alfredapp.com/help/workflows/automations/automation-task/#update).

**Comment by JohnMaguire** [comment]
@vitorgalvao Thank you for the link! I figured this might be the issue but was really struggling to figure out how to get them. This fixed it.
