### ISSUE TITLE
"sign in and update items" does nothing

### ISSUE THREAD

**Issue by aharpole** [alfredapp/1password-workflow#69]
### Diagnostic

Hi! I just installed the workflow and the 1password CLI. I have signed in on the CLI and enabled the CLI integration in 1Password 8, but when I try to use the workflow, I just get the "sign in and update items" result and when I hit Enter, nothing happens.

### Workflow version
2023.11

### Alfred version
5.1.3

### macOS version
14.0

### Architecture
arm64

### Preferences
Dict {
}

### 1Password version
8.10.16

### op version
2.21.0

### Launchd job
NOT loaded
NOT installed

### More details

I tried resetting the workflow to defaults and restarting Alfred, but nothing happened.

**Comment by vitorgalvao** [comment]
Something *always* happens. Without the debugger output it’s impossible to diagnose further.

Also, what happens when you run `op item list` in a Terminal?

**Comment by erawhctim** [comment]
I'm running into this same error, and ran through the exact same steps as @aharpole. My version numbers are all identical, and I'm on arm64 as well.

Here's my debugger output: 
```
[12:17:37.340] 1Password[Script Filter] Queuing argument '(null)'
[12:17:37.383] 1Password[Script Filter] Script with argv '(null)' finished
[12:17:37.394] 1Password[Script Filter] {
  "rerun": 0.1,
  "items": [{
    "variables": { "action": "update_items" },
    "title": "Sign in and update items",
    "arg": "update_items",
    "icon": { "path": "composite_icon.png" }
  }]
}
[12:17:37.489] 1Password[Script Filter] Queuing argument '(null)'
[12:17:37.595] 1Password[Script Filter] Script with argv '(null)' finished
[12:17:37.608] 1Password[Script Filter] {
  "rerun": 0.1,
  "items": [{
    "variables": { "action": "update_items" },
    "title": "Sign in and update items",
    "arg": "update_items",
    "icon": { "path": "composite_icon.png" }
  }]
}
[12:17:37.694] 1Password[Script Filter] Queuing argument '(null)'
[12:17:37.722] 1Password[Script Filter] Processing complete
[12:17:37.727] 1Password[Script Filter] Passing output 'update_items' to Junction
[12:17:37.731] 1Password[Junction] Processing complete
[12:17:37.736] 1Password[Junction] Passing output 'update_items' to Automation Task
[12:17:37.740] ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/macOS/app.running'
```

The beginning bit with `Queuing argument '(null)'`, `Script with argv '(null)' finished`, and the JSON output seems to run in a giant loop a million times.

What are we missing here? Is this a bug, or user error?

**Comment by vitorgalvao** [comment]
@erawhctim [Same question](https://github.com/alfredapp/1password-workflow/issues/69#issuecomment-1757075015):

> what happens when you run `op item list` in a Terminal?

**Comment by bheltzel** [comment]
> @erawhctim:
> 
> > ERROR: 1Password[Automation Task] Task not found 'com.alfredapp.automation.core/macOS/app.running'
> 
> You need to [install the Automation Tasks](https://www.alfredapp.com/help/workflows/automations/automation-task/#update).

This is only available in Alfred 5, so I think the workflow is not supported in Alfred 4 or older? Might be worth adding to your Readme - I spent a good bit of time trying to figure this out too. Thanks!
