### ISSUE TITLE
Failing to see just logins as results

### ISSUE THREAD

**Issue by brunorsini** [alfredapp/1password-workflow#74]
### Workflow version
2023.12

### Alfred version
5.1.4

### macOS version
13.5.2

### Architecture
arm64

### Preferences
Dict {
    logins_only = true
}

### 1Password version
8.10.20

### op version
2.23.0

### Launchd job
NOT loaded
NOT installed

### Debugger output

```codeblock
?
```

### More details

Hi!

Even though   logins_only = true (see above), when I do "1p <query>" I see credit cards, text notes, etc. Can you pls help fix this? All I want is to find the right login, press enter and have a new tab be open + 1Password automatically fill out the login info for me.

Really appreciate the help.

Bruno

**Comment by vitorgalvao** [comment]
After enabling the option, you have to `:1pextras` → `Force Update Items`.
