### ISSUE TITLE
Display Password

### ISSUE THREAD

**Issue by stacksjb** [alfredapp/1password-workflow#76]
### Feature details

Hello,

I have a few sites where I cannot use copy/paste (such as remote RDP) but need to be able to view the password for entry.

How can I customize a hotkey for "display password" instead of copy password? I tried to see if I could just customize workflow to reassign a parameter, but it doesn't look like a parameter exists for that in the workflow currently.

**Comment by vitorgalvao** [comment]
> How can I customize a hotkey for "display password" instead of copy password?

Doing anything that requires reading a password will also require authenticating with the 1Password tool, because for security and privacy reasons the workflow never stores those.

How exactly did you envision the displaying of the password?

**Comment by stacksjb** [comment]
The ideal way I envisioned it would be to be able to just display it in the alfred search results  (if logged in)
If not logged in then have you prompt for login before returning.

A workflow where it is shown in a notification would work, but I could see security issues with that. 

Sending the text to The "Large Type" output would meet my needs perfectly.

**Comment by vitorgalvao** [comment]
Looked into it and decided it was best to not add it. The workflow goes to great lengths to never even see your password. E.g. when copying it doesn’t even pass the result between objects but I’ve made it copy directly in the script with the special flag to not show up in the clipboard history. Any change here to display it would lower the security, which I actively avoid. Mind you, the decrease wouldn’t be severe, but we’re talking a niche request which could potentially have people shoot themselves in the foot and preventing that is especially important in a workflow of this nature. [Usernames are also not saved out of an abundance of caution](https://github.com/alfredapp/1password-workflow/issues/59#issuecomment-1576443204).

One option it to disable `Ignore clipbiard data marked as Concealed` in Alfred Preferences → Clipboard History → Advanced, **which I do not recommend**. But that would allow you to view your entries from Clipboard History and even <kbd>⌘</kbd><kbd>L</kbd> to show Large Type. You can delete individual items with <kbd>fn</kbd><kbd>⌫</kbd>.

If I come up with a way to do it without compromises, I’ll revisit it.

Thank you for the request.

**Comment by stacksjb** [comment]
Hmm. I appreciate the comments. I agree we don't want it shown in clipboard history or similar - that's why I suggested a route to simply display on screen using one of the display/output options (such as large type)

What about executing the "op item get <itemid>" command in the CLI as an option? That would then bring it to the forefront.

I assume onepassword doesn't give you a way to integrate with the desktop app and tell it to display the item? (the "Show in large type" option within onepassword does exactly what I need, it just takes a few extra clicks and would be ideal to automate showing, but I'm not sure if you can tell it to do that through the CLI).

I can certainly take that feedback to them as a possible feature.

**Comment by vitorgalvao** [comment]
> I assume onepassword doesn't give you a way to integrate with the desktop app and tell it to display the password? (the "Show in large type" option within onepassword does exactly what I need

Interesting idea, that could work because I’d only need to pass the identifier to the item and account and let the 1Password app handle it securely. There is already an option to `View in 1Password` which gets us closer. That uses 1Password’s URL handler (`onepassword://`), which unfortunately isn’t documented (that I know of) so I only know of a couple specific things it can do. In other words, I’m not sure if they currently have a way to force 1Password’s large type output from the outside. But if you find it or they add it (seems like a valid feature request for the URL handler) I’ll definitely consider that route.

**Comment by vitorgalvao** [comment]
> using one of the display/output options (such as large type)

To expand further on this, the problem there is it would mean Alfred itself would need to pass the result between objects, making it visible in [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/). Now imagine a situation where someone has an issue and I need the debugger output to diagnose. Depending on what they’re doing, they could inadvertently paste the password to a public issue. I don’t want to give people ways to shoot themselves in the foot, it’s important that the workflow be as secure as can be.
