### ISSUE TITLE
Stuck on updating items

### ISSUE THREAD

**Issue by emrishe** [alfredapp/1password-workflow#77]
### Workflow version
2023.12

### Alfred version
5.1.4

### macOS version
14.3

### Architecture
arm64

### Preferences
Default

### 1Password version
8.10.24

### op version
2.23.0

### Launchd job
Loaded: -	0	com.alfredapp.vitor.1password
Installed

**Comment by vitorgalvao** [comment]
Without the debugger output, it’s impossible to diagnose whatever you’re facing. Also, please follow the steps in the the forum’s [second post](https://www.alfredforum.com/topic/18275-1password-—-search-and-open-1password-items/#comment-94793).

**Comment by vitorgalvao** [comment]
This is not a feature request. Please open a proper [bug report](https://github.com/alfredapp/1password-workflow/issues/new?assignees=&labels=&projects=&template=bug_report.yml) and include the debugger output, without which it’s impossible to diagnose whatever you’re facing. Also, please follow the steps in the the forum’s [second post](https://www.alfredforum.com/topic/18275-1password-—-search-and-open-1password-items/#comment-94793).
