### ISSUE TITLE
Where is it getting these "login items"?

### ISSUE THREAD

**Issue by kellyarwine** [alfredapp/1password-workflow#80]
### Diagnostic

Not required

### Debugger output

Not required

### More details

I'm having a problem. Here's an example of what I'm experiencing. I have a Target Redcard (it's a credit card for a major retailer in the US). I have a login for the credit card website stored in 1Password and the actual credit card number. For some reason, other items pop up when I start to search for "redcard". IThe same search in the 1Password app only returns the two items: credit card and website login. I have the option set to only show login items in Alfred so I would expect to only see the credit card website login in Alfred. Oddly, I'm getting a google.com entry and a todoist entry?

Before pasting any diagnostic info maybe someone can point out something obvious I'm missing.

![Image](https://github.com/alfredapp/1password-workflow/assets/2262535/68a9fd21-80e3-4b2b-b1b0-fb0b50239704)

**Comment by vitorgalvao** [comment]
* Start by running `:1pextras` → Force Update Items. Then try again.
* If it persists, open those entries via the workflow and see where they lead.

If none of those work, the diagnostic and debugger output are necessary.

**Comment by aheckler** [comment]
Try unchecking this in the workflow configuration:

![Screenshot taken on 2024-05-19 at 10 31 42 UTC@2x](https://github.com/alfredapp/1password-workflow/assets/5512652/c5866ae1-4c05-44a3-a9e2-b56345b8bec5)

... and then using `:1pextras` → Force Update Items. Does that help?
