### ISSUE TITLE
Pop notification once password is fetched

### ISSUE THREAD

**Issue by bevanjkay** [alfredapp/1password-workflow#81]
### Feature details

I often use the extension to copy a password for a service to the clipboard, but I find myself regularly trying to paste before the password is available. I'd love a feature that allows enabling a notification to let me know once the password has successfully added to my clipboard.

**Comment by vitorgalvao** [comment]
Makes sense. It would be preferable if it happened faster, but that bit is unfortunately out of my control. The notification is a good compromise. I have also added a sound so you don’t need to look.

Mind giving [this version](https://github.com/user-attachments/files/15586337/1Password.alfredworkflow.zip) a quick spin before it’s released?

**Comment by vitorgalvao** [comment]
Thank you. New release is now live.
