### ISSUE TITLE
Error when trying to "View in 1Password" action

### ISSUE THREAD

**Issue by carlosg-stripe** [alfredapp/1password-workflow#82]
### Workflow version
2024.2

### Alfred version
5.5

### macOS version
14.5

### Architecture
arm64

### Preferences
Dict {
    mod_cmd = open_and_fill
    mod_none = view_in_1password
}

### 1Password version
8.10.34

### op version
2.29.0

### Launchd job
NOT loaded
NOT installed

### Debugger output

```codeblock
[10:49:11.932] ERROR: 1Password[Automation Task] Task Error (127): /bin/zsh: can't open input file: /Users/(username)/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/Automation Tasks/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

### More details

The folder exists on my filesyste, but it seems to be empty: 
```
$ ll /Users/(username)/Library/Caches/com.runningwithcrayons.Alfred/Workflow\ Scripts/Automation\ Tasks/
total 0
drwxr-xr-x  2 (username)  staff    64B 25 Jun 13:44 .
drwxr-xr-x  6 (username)  staff   192B  2 Jul 10:49 ..
```

**Comment by vitorgalvao** [comment]
[Update the Automation Tasks](https://www.alfredapp.com/help/workflows/automations/automation-task/#update) then reboot your Mac and try again.

**Comment by carlosg-stripe** [comment]
Too easy 😅, worked like a charm. Thanks for the quick reply!
